# fly.toml app configuration file generated for rough-paper-3061 on 2023-08-15T11:22:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rough-paper-3061"
primary_region = "yyz"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
